default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: E2B5123@
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_rails_development
test:
  <<: *default
  database: blog_app_rails_test

production:
  <<: *default
  database: blog_app_rails_production
  username: blog_app_rails
  password: <%= ENV["BLOG_APP_RAILS_DATABASE_PASSWORD"] %>
